routes/web.php
<?php

Auth::routes([
    'register' => true
]);

Route::get('/', 'PageController@home');

Route::resource('zenders', 'ZenderController');
Route::resource('programma', 'ProgrammaController');
Route::get('zenders/search', 'ZenderController@search')->name('zenders.search');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/users', 'UsersController', ['except' =>['show', 'create', 'store']]);
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function hasAnyRoles($roles) {

        if($this->roles()->whereIn('name', $roles)->first()){
            return true;
        }
        return false;
    }

    public function hasRole($role) {

        if($this->roles()->where('name', $role)->first()){
            return true;
        }
        return false;
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Role;
use Illuminate\Support\Facades\Gate;
use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Gate::denies('index-users')){
            return redirect('/');
        }
        $users = User::all();
        return view('admin.users.index')->with('users', $users);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all();

        return view('admin.users.edit')->with([
            'user' => $user,
            'roles' => $roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->roles()->sync($request->roles);

        $user->name = $request->name;
        $user->email = $request->email;
        $user->save();


        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.layout')

@section('content')
        <div class="column">
            <div class="card">
                <div class="card-header">
                    <h3 class="has-margin-left-20 has-margin-top-10"> Edit user {{ $user->name }} </h3>
                </div>
                    <div class="card-content">
                    <form action="{{ route('admin.users.update', $user) }}" method="POST">

                        <div class="field">
                            <label class="label" for="name">Email</label>
                            <div>
                                <input id="email" type="text" class="control input @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email" autofocus>

                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="field">
                            <label class="label" for="name">Naam</label>
                            <div>
                                <input id="name" type="text" class="control input @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required autofocus>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        @csrf
                        {{ method_field('PUT') }}
                        <div class="field">
                            <label class="label" for="roles">Rollen</label>
                        @foreach($roles as $role)
                            <div class="field">
                                <input type="checkbox" name="roles[]" value="{{ $role->id }}"
                                 @if($user->roles->contains($role->id)) checked=checked @endif>
                                <label>{{ $role->name }}</label>
                            </div>
                            @endforeach
                        </div>
                                <button type="submit" class="button is-primary">
                                    Update
                        </button>
                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.layout')

@section('content')
        <div class="column">
            <div class="card">
                <div class="card-header">
                    <h3 class="has-margin-left-20 has-margin-top-10">Users</h3>
                </div>
                    <div class="card-content">
                        <table class="table is-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Naam</th>
                                <th>Email</th>
                                <th>Rol</th>
                                <th>Actie</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <th>{{ $user ->id }}</th>
                                    <td>{{ $user ->name }}</td>
                                    <td>{{ $user ->email }}</td>
                                    <td>{{ implode(',',$user ->roles()->get()->pluck('name')->toArray()) }}</td>
                                    <td>
                                        <a href="{{ route('admin.users.edit', $user->id) }}"><button type="button" class="button is-warning is-pulled-left">Edit</button></a>
                                        <form action="{{ route('admin.users.destroy', $user) }}" method="POST" class="is-pulled-left">
                                            @csrf
                                            {{ method_field('DELETE') }}
                                            <button type="submit" class="button is-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
            </div>
        </div>

@endsection