routes/web.php
<?php

Auth::routes([
    'register' => true
]);

Route::get('/', 'PageController@home');

Route::resource('zenders', 'ZenderController');
Route::resource('programma', 'ProgrammaController');
Route::get('zenders/search', 'ZenderController@search')->name('zenders.search');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/users', 'UsersController', ['except' =>['show', 'create', 'store']]);
});

app/Zenders.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Zenders extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'naam', 'inhoud', 'slugs', 'id'
    ];
}

app/Http/Controllers/ZenderController.php
<?php

namespace App\Http\Controllers;

use App\Programma;
use Illuminate\Http\Request;
use App\Zenders;
use Illuminate\Http\Response;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;


class ZenderController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['only' => ['edit', 'create', 'store', 'destroy']]);

    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $zenders = Zenders::orderBy('naam')->paginate(env('APP_PAGINATION_LIMIT', 6));

        return view('zenders.index', compact('zenders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {

        return view('zenders.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     * @throws ValidationException
     */
    public function store(Request $request)
    {
        //Data Valideren
        $this->validate(
            $request, [
            'naam' => 'required|min:1|unique:zenders,naam,NULL,id,deleted_at,NULL',
            'inhoud' => 'required',
        ]);
        //Data opslaan in database
        $zenders = new Zenders;
        $zenders->naam = $request->naam;
        $zenders->body = $request->inhoud;
        $zenders->slug = Str::slug($request->naam, '-');


        //Data versuren naar een applicatie
        $zenders->save();

        return redirect()->route('zenders.show', $zenders->slug)->with('success', 'Zender aangemaakt');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        // Zet de slug variable als url
        $slug = strtolower($id);
        $zenders = Zenders::where('slug', '=', $slug)->get()->first();
        if (!$zenders) {
            abort(404);
        }

        return view('zenders.show', compact('zenders'));
    }


/*    public function search(Request $request)
    {
        $terms = new Collection();
        $query = $request->get('query');
        $category = $request->get('category_id');
        if ($query || $category) {
            $termsQuery = Terms::with('categories');
            if ($category) {
                $termsQuery->whereHas('categories', function ($q) use ($category) {
                    $q->where('categories_id', $category);
                });
            }
            if ($query) {
                $termsQuery->where('title', 'like', '%' . $query . '%');
            }

            $terms = $termsQuery->paginate(env('APP_PAGINATION_LIMIT', 5));

        }
        return view('terms.index', compact('terms'));
    }*/


    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        // Zet de slug variable als url
        $slug = strtolower($id);
        $zenders = Zenders::where('slug', '=', $slug)->get()->first();
        if (!$zenders) {
            abort(404);
        }
        return view('zenders.edit', compact('zenders'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     * @throws ValidationException
     */
    public
    function update(Request $request, $id)
    {
        //Data Valideren
        $this->validate(
            $request, [
            'naam' => 'required|min:1|unique:zenders,naam,NULL,id,deleted_at,NULL' . $id,
            'inhoud' => 'required',
        ]);

        $slug = strtolower($id);
        $zenders = Zenders::where('slug', '=', $slug)->get()->first();
        if (!$zenders) {
            abort(404);
        }

        //Data opslaan in database
        $zenders->naam = $request->naam;
        $zenders->body = $request->inhoud;
        $zenders->slug = Str::slug($request->naam, '-');

        //Data versuren naar een applicatie
        $zenders->save();

        //Kopelt de term aan een categorie in de pivot table
        return redirect()->route('zenders.show', $zenders->slug)->with('success', 'Zender aangepast');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public
    function destroy($id)
    {
        // Zet de slug variable als url
        $slug = strtolower($id);
        $zenders = Zenders::where('slug', '=', $slug)->get()->first();
        if (!$zenders) {
            abort(404);
        }

        $response = "Je hebt {$zenders->naam} verwijderd";
        $zenders->delete();

        return redirect()->route('zenders.index')->with('deleted', $response);
    }
}

resources/views/zenders/create.blade.php
@extends ('layouts.layout')
@section('title','Zender toevoegen')
@section('h1','Zender toevoegen')
@section ('content')
    <form id="save_post" method="POST" action="{{route('zenders.store')}}">
        @csrf

        <div class="columns">
            <div class="column">
                <label for="name"><h2>Zender</h2></label>
                <input type="text" id="naam" class="input" name="naam" value="{{ old('naam') }}">
            </div>
        </div>

        <div class="columns">
            <div class="column">
                <label for="name"><h2>Omschrijving</h2></label>
                <textarea id="editor" class="input" style="height: 145px;" name="inhoud">{{ old('inhoud') }}</textarea>
            </div>
        </div>


        <div class="columns">
            <div class="column">
                <input type="submit" class="button is-success" value="Opslaan">
            </div>
        </div>

    </form>
@endsection

resources/views/zenders/edit.blade.php
@extends('layouts.layout')
@section('title', $zenders->title)
@section('h1', 'De zender '.$zenders->naam.' aanpassen')
@section('content')
    <form method="post" action="{{ route('zenders.update', $zenders->slug) }}">

        <div class="columns">
            @csrf
            @method('PATCH')
            <div class="column">
                <label for="name"><h2>Naam</h2></label>
                <input type="text" class="input" name="naam" value="{{ $zenders->naam }}">
            </div>
        </div>

        <div class="columns">
            <div class="column">
                <label for="name"><h2>Omschrijving</h2></label>
                <textarea id="editor" class="input" style="height: 190px;" name="inhoud">{{ $zenders->body }} </textarea>
            </div>
        </div>

        <div class="columns">
            <div class="column">
                <button type="submit" class="button is-success">Opslaan</button>
            </div>
        </div>
    </form>
@endsection

resources/views/zenders/index.blade.php
@extends ('layouts.layout')

@section('title', 'Zenders')
@section('bodyclass','index')

@section('h1', 'Zenders')

@section('content')
    @guest
        <div class="columns">
            <div class="column has-text-centered">
                <a href="/contact" class="button is-rounded is-success is-outlined">Neem contact op</a>
            </div>
        </div>
    @else
        <div class="columns">
            <div class="column has-text-centered">
                <a href="{{route('zenders.create')}}" class="button is-rounded is-success">Maak een nieuwe zender aan</a>
            </div>
        </div>
    @endguest
    @guest
        @else
    <form action="{{route('zenders.search')}}" method="get">
        <div class="columns has-text-centered">
            <div class="column is-half">
                <input type="text" value="{{ app('request')->get('query') }}" name="query" class="input is-rounded"
                       placeholder="Programma/Zender zoeken">
            </div>
            <div class="column has-text-centered ">
                <button type="submit" class="button is-rounded is-info is-fullwidth is-outlined">Zoeken</button>
            </div>
        </div>
    </form>
    @endguest
    <div class="columns has-margin-top-50">
        @forelse($zenders as $key => $data)
            @if($loop->index >= 2 && $loop->index % 3 == 0)
    </div>
    <div class="columns">
        @endif
        <div class="column is-one-third">
            <div class="index">

                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">
                            {{ substr(strip_tags($data->naam), 0,60)}}{{ strlen(strip_tags($data->naam)) >  60 ? "..." : ""}}
                        </p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            {!! substr(strip_tags($data->body), 0,120)!!}{!! strlen(strip_tags($data->body)) >120 ? "..." : ""!!}
                        </div>
                      </div>
                    <footer class="card-footer">
                        <a href="{{route('zenders.show', $data->slug)}}" class="card-footer-item button is-info">Programmaoverzicht</a>
                        @guest
                        @else
                            <a class="card-footer-item button is-warning"
                               href="{{route('zenders.edit', $data->slug)}}">Edit</a>
                        @endguest
                    </footer>
                </div>
            </div>
         </div>



        @empty
            <th><h3>Geen zenders gevonden</h3></th>
        @endforelse
    </div>
    @if(!$zenders->isEmpty())
        {{ $zenders->appends(request()->input())->links() }}
    @endif
@stop

resources/views/zenders/show.blade.php
@extends ('layouts.layout')
@section('title',$zenders->naam)


@section ('content')
    <div class="content">
            @guest
                <div class="column is-one-third">
                    <div class="card">
                        <div class="card-content">
                            <h2 class="lead"> {!! $zenders->naam !!}</h2>
                            <h2 class="lead"> {!! $zenders->body!!}</h2>
                        </div>
                    </div>
                </div>

            @else

                <div class="column is-one-third">
                    <div class="card">
                        <div class="card-content">
                                <h2 class="lead"> {!! $zenders->naam !!}</h2>
                                <h2 class="lead"> {!! $zenders->body!!}</h2>
                            </div>
                            <footer class="card-footer">
                                <a href="{{ route('zenders.edit', $zenders->slug) }}"
                                   class="card-footer-item button is-warning">Aanpassen</a>
                                <a class="card-footer-item button is-danger"
                                   onclick="checkBeforeSubmit()">Verwijderen</a>
                                <script>
                                    function checkBeforeSubmit() {
                                        if (!confirm('Weet je zeker dat je dit wil verwijderen?')) return;
                                        document.getElementById('delete-form').submit();
                                    }
                                </script>

                                <form id="delete-form" action="{{ route('zenders.destroy', $zenders->slug) }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            </footer>
                        </div>
                    </div>
                    @endguest
                </div>
@endsection